### ISSUE TITLE
Add placeholder support

### ISSUE THREAD

**Issue by JayAshday** [renanborgez/react-nice-input-password#2]
It looks like the InputLabel sub-component supports placeholders, but the NiceInputPassword component does not. Would it be possible for NiceInputPassword to have a "placeholder" prop that just gets sent on to the InputLabel?

**Comment by renanborgez** [comment]
@JayAshday 
I'm planning to update the library to fix some security issues and i will also support the placeholder.

I hope i can do it in the next week. But also feel free to open PR.

Sorry, i am almost 1 year delayed

**Comment by renanborgez** [comment]
@JayAshday Version 2.3.1
