### ISSUE TITLE
Importing issues in Typescript (Next JS)

### ISSUE THREAD

**Issue by JithinAntony4** [renanborgez/react-nice-input-password#23]
when I started importing it shows like 
`ReferenceError: window is not defined this error happened while generating the page. Any console logs will be displayed in the terminal window.`
` module.exports = require("react-nice-input-password");`

[Screenshot](https://i.snipboard.io/iBIySE.jpg)

**Comment by renanborgez** [comment]
@JithinAntony4 are you using this on the backend?

**Comment by JithinAntony4** [comment]
@renanborgez Yes

**Comment by renanborgez** [comment]
I haven't setup this plugin for server side rendering yet
however as far as I know you can import the plugin like this by using nextjs

```js
import dynamic from "next/dynamic"

const NiceInputPassword = dynamic(() => import('react-nice-input-password'), {ssr: false});
```

I tried it locally and it does work!

**Comment by renanborgez** [comment]
I'm going to update the documentation adding this snippet to help other nextjs users

**Comment by JithinAntony4** [comment]
> I haven't setup this plugin for server side rendering yet
> however as far as I know you can import the plugin like this by using nextjs
> 
> ```js
> import dynamic from "next/dynamic"
> 
> const NiceInputPassword = dynamic(() => import('react-nice-input-password'), {ssr: false});
> ```
> 
> I tried it locally and it does work!

it's working!
