### ISSUE TITLE
customisation of textfield using css

### ISSUE THREAD

**Issue by bipindubey-technoark** [renanborgez/react-nice-input-password#7]
I need to customize textfield css but its not working ..Please Help 
Thank You

**Comment by renanborgez** [comment]
hello @bipindubey-technoark 

nice that you are using the component.

To be able to customise the textfield css, you can do this by using the `className` property and targeting your css to the `input` field.

![image](https://user-images.githubusercontent.com/1863024/91970028-55ef5380-ed17-11ea-92e5-87570972fcec.png)
![image](https://user-images.githubusercontent.com/1863024/91970302-bda59e80-ed17-11ea-8653-8a45bbb705db.png)
![image](https://user-images.githubusercontent.com/1863024/91970166-88994c00-ed17-11ea-9a53-a0510eee6c02.png)

https://codesandbox.io/s/o1v16rqqrz
(check the last NiceInputPassword example)

**Comment by bipindubey-technoark** [comment]
Thanks @renanborgez for your quick reply 
It worked for me 
Is there any way i can put eye icon at the end for visibility toggle.

**Comment by renanborgez** [comment]
@bipindubey-technoark sounds very nice feature and quite simple
give me some time and I'll implemented it because I think I'm also going to use it :) 
and then I'll reply to you in this thread

**Comment by bipindubey-technoark** [comment]
Ok no problem @renanborgez  and thanks Again :)
I have all the logic for toggle visibility and previously i was using custom input and i had added eye icon there and it was working but now i have integrated your component so i am not able to do this so please solve it as soon as possible.
and Can you give some timeline till when it is done?

**Comment by bipindubey-technoark** [comment]
I want something like startAdornment and endAdornment we used in material ui component
Thanks @renanborgez

**Comment by renanborgez** [comment]
@bipindubey-technoark that is precisely what I was thinking too :)

**Comment by bipindubey-technoark** [comment]
![Screenshot from 2020-09-02 16-35-12](https://user-images.githubusercontent.com/59605232/91973705-51886200-ed3a-11ea-89f8-6f7a9964b5a5.png)

**Comment by bipindubey-technoark** [comment]
I will wait for your reply @renanborgez 
I need to deploy my changes as soon as possible because it is gone live

**Comment by bipindubey-technoark** [comment]
Any update? @renanborgez

**Comment by renanborgez** [comment]
Unlike the material ui which has its own styles, I left the adornments styleless
I'm going to update the codesandbox demo, but basically it places the adornments in the beginning and in the end of the input field

if you want to place it like the material ui, you just need to apply styles for it, like positioning as absolute and etc...

check #10

**Comment by bipindubey-technoark** [comment]
Ok Thanks!!! @renanborgez

**Comment by bipindubey-technoark** [comment]
one more thing we dont have type props here like if user has clicked on eye icon i am basically changing the type of input from password to text so how to do this here

**Comment by renanborgez** [comment]
currently it is not possible, the idea of this component was about to create input password but I think it also not a problem to have it

**Comment by renanborgez** [comment]
working on that

**Comment by bipindubey-technoark** [comment]
ok

**Comment by bipindubey-technoark** [comment]
Any issue?

**Comment by bipindubey-technoark** [comment]
now can you give some examples related to icon added and type in codesandbox
give basic example

**Comment by bipindubey-technoark** [comment]
Thanks @renanborgez  for your precious help.
Thanks Again @renanborgez
